#!/usr/bin/env Rscript
# Publication header
# Step: 05_gsva_analysis
# Purpose: Figure 5 single-cell R-star/GSVA processing or plotting
# Inputs: /mnt/f/13_scMR_/results/figure5/single_cell_expand2_revised/plots_circular/pd_only_subcell_expand2_sc_rstar_circular_summary.tsv; /mnt/f/13_scMR_/results/figure5/single_cell_expand2_revised/plots_circular; _plotting_table.tsv; _legend.pdf
# Input schema: Schema: not fully inferable from script; known columns should be verified against upstream data dictionaries or script-level read statements.
# Outputs: /mnt/f/13_scMR_/results/figure5/single_cell_expand2_revised/plots_circular/pd_only_subcell_expand2_sc_rstar_circular_summary.tsv; /mnt/f/13_scMR_/results/figure5/single_cell_expand2_revised/plots_circular; _plotting_table.tsv; _legend.pdf
# Output schema: Schema: not fully inferable from script; preserve existing output filenames and columns.
# How to run: from this script directory, run `Rscript 21_make_pd_single_cell_rstar_circlize_barplot.R` unless a project-specific driver script documents otherwise.
# Dependencies: circlize, ComplexHeatmap, grid
# Notes: Added during publication code-cleaning. This header is documentation only and does not change scientific logic, thresholds, statistical methods, filtering rules, model parameters, random seeds, figure values, or output content.


# Circlize-style PD-only single-cell R* circular barplot for Figure 5.
# Input is the summary TSV generated by 20_make_pd_single_cell_rstar_circular_barplot.py:
#   pd_only_subcell_expand2_sc_rstar_circular_summary.tsv
# Required columns:
#   cohort, parent_cell_type, subcell_label, Rstar, NES_risk, NES_protective, n_cells, n_donors

suppressPackageStartupMessages({
  library(circlize)
})

get_arg <- function(name, default=NULL) {
  args <- commandArgs(trailingOnly=TRUE)
  key <- paste0("--", name, "=")
  hit <- grep(paste0("^", key), args, value=TRUE)
  if (length(hit) == 0) return(default)
  sub(key, "", hit[[1]], fixed=TRUE)
}

input_file <- get_arg("input", "/mnt/f/13_scMR_/results/figure5/single_cell_expand2_revised/plots_circular/pd_only_subcell_expand2_sc_rstar_circular_summary.tsv")
out_dir <- get_arg("outdir", "/mnt/f/13_scMR_/results/figure5/single_cell_expand2_revised/plots_circular")
prefix <- get_arg("prefix", "figure5_pd_only_sc_Rstar_expand2_circlize_barplot")
label_cex <- as.numeric(get_arg("label_cex", "0.36"))
parent_cex <- as.numeric(get_arg("parent_cex", "0.82"))
cohort_cex <- as.numeric(get_arg("cohort_cex", "1.15"))
fig_width <- as.numeric(get_arg("width", "9.5"))
fig_height <- as.numeric(get_arg("height", "9.5"))
max_label_len <- as.integer(get_arg("max_label_len", "32"))
min_cells <- as.integer(get_arg("min_cells", "20"))
min_donors <- as.integer(get_arg("min_donors", "1"))

if (!file.exists(input_file)) {
  stop("Summary input not found: ", input_file)
}
dir.create(out_dir, recursive=TRUE, showWarnings=FALSE)

message("[read] ", input_file)
d <- read.delim(input_file, check.names=FALSE, stringsAsFactors=FALSE)
required <- c("cohort", "parent_cell_type", "subcell_label", "Rstar", "NES_risk", "NES_protective")
missing <- setdiff(required, colnames(d))
if (length(missing) > 0) stop("Missing columns: ", paste(missing, collapse=", "))

if ("n_cells" %in% colnames(d)) d <- d[d$n_cells >= min_cells, , drop=FALSE]
if ("n_donors" %in% colnames(d)) d <- d[d$n_donors >= min_donors, , drop=FALSE]

# Strict final four-block order.
block_map <- data.frame(
  cohort = c("dlPFC", "dlPFC", "snPC", "snPC"),
  parent_cell_type = c("IN", "EN", "dopaminergic neuron", "inhibitory interneuron"),
  block = c("dlPFC | IN", "dlPFC | EN", "SNpc | dopaminergic neuron", "SNpc | inhibitory interneuron"),
  block_order = 1:4,
  stringsAsFactors=FALSE
)

d <- merge(d, block_map, by=c("cohort", "parent_cell_type"), all.x=FALSE, all.y=FALSE)
if (nrow(d) == 0) stop("No rows left after matching the four expected blocks.")

# Sort sub-cell labels by mean PD R* within each block, descending.
d <- d[order(d$block_order, -d$Rstar, d$subcell_label), , drop=FALSE]
d$block <- factor(d$block, levels=block_map$block)

# Write the exact plotting table for provenance.
plot_tsv <- file.path(out_dir, paste0(prefix, "_plotting_table.tsv"))
write.table(d, plot_tsv, sep="\t", quote=FALSE, row.names=FALSE)
message("[write] ", plot_tsv)

short_label <- function(x, n=max_label_len) {
  x <- as.character(x)
  ifelse(nchar(x) > n, paste0(substr(x, 1, n - 1), "…"), x)
}

# Symmetric ranges make negative and positive bars comparable.
sym_lim <- function(x, floor_abs=0.25) {
  m <- max(abs(x), na.rm=TRUE)
  m <- max(m, floor_abs)
  c(-m, m)
}

rstar_ylim <- sym_lim(d$Rstar)
risk_ylim <- sym_lim(d$NES_risk)
prot_ylim <- sym_lim(d$NES_protective)

# Quantile winsorized color ranges avoid one extreme subtype dominating the palette.
qabs <- function(x, q=0.98, floor_abs=0.25) {
  max(as.numeric(quantile(abs(x), q, na.rm=TRUE)), floor_abs)
}
rstar_q <- qabs(d$Rstar)
risk_q <- qabs(d$NES_risk)
prot_q <- qabs(d$NES_protective)

col_rstar <- colorRamp2(c(-rstar_q, 0, rstar_q), c("#2166AC", "#F7F7F7", "#B2182B"))
col_risk <- colorRamp2(c(-risk_q, 0, risk_q), c("#D9D9D9", "#F7F7F7", "#7B3294"))
col_prot <- colorRamp2(c(-prot_q, 0, prot_q), c("#D9D9D9", "#F7F7F7", "#1B7837"))

block_cols <- c(
  "dlPFC | IN" = "#E8EEF7",
  "dlPFC | EN" = "#F1E8F7",
  "SNpc | dopaminergic neuron" = "#F8EFE0",
  "SNpc | inhibitory interneuron" = "#E7F2E8"
)

# Sectors proportional to number of sub-cell labels.
block_levels <- levels(d$block)
block_n <- as.integer(table(d$block)[block_levels])
names(block_n) <- block_levels
xlim <- cbind(rep(0, length(block_n)), block_n)
rownames(xlim) <- block_levels

# Larger gaps between cohorts than within cohort.
gap_after <- c(3, 13, 3, 13)

make_plot <- function(device_fun, file, width=fig_width, height=fig_height) {
  device_fun(file, width=width, height=height)
  on.exit(dev.off(), add=TRUE)
  par(mar=c(1, 1, 1, 1), xpd=NA)
  circos.clear()
  circos.par(
    start.degree = 90,
    gap.after = gap_after,
    track.margin = c(0.004, 0.004),
    cell.padding = c(0, 0, 0, 0),
    points.overflow.warning = FALSE,
    canvas.xlim = c(-1.32, 1.32),
    canvas.ylim = c(-1.32, 1.32)
  )
  circos.initialize(factors=block_levels, xlim=xlim)

  # Track 1: parent cell-type blocks.
  circos.trackPlotRegion(
    ylim=c(0, 1), track.height=0.055, bg.border=NA,
    panel.fun=function(x, y) {
      sector <- CELL_META$sector.index
      circos.rect(CELL_META$xlim[1], 0, CELL_META$xlim[2], 1,
                  col=block_cols[[sector]], border=NA)
      circos.text(mean(CELL_META$xlim), 0.52, sub("^.* \\| ", "", sector),
                  facing="bending.outside", niceFacing=TRUE,
                  cex=parent_cex, font=2, col="#222222")
    }
  )

  # Track 2: subtype/author labels above outermost bars.
  circos.trackPlotRegion(
    ylim=c(0, 1), track.height=0.18, bg.border=NA,
    panel.fun=function(x, y) {
      sector <- CELL_META$sector.index
      ss <- d[d$block == sector, , drop=FALSE]
      if (nrow(ss) == 0) return(NULL)
      pos <- seq_len(nrow(ss)) - 0.5
      circos.text(pos, 0.03, short_label(ss$subcell_label),
                  facing="clockwise", niceFacing=TRUE,
                  adj=c(0, 0.5), cex=label_cex, col="#2A2A2A")
    }
  )

  draw_bar_track <- function(value_col, ylim, col_fun, track_title) {
    circos.trackPlotRegion(
      ylim=ylim, track.height=0.115, bg.border="#E5E5E5",
      panel.fun=function(x, y) {
        sector <- CELL_META$sector.index
        ss <- d[d$block == sector, , drop=FALSE]
        if (nrow(ss) == 0) return(NULL)
        pos <- seq_len(nrow(ss)) - 0.5
        vals <- ss[[value_col]]
        circos.barplot(vals, pos, col=col_fun(vals), border=NA)
        circos.lines(CELL_META$xlim, c(0, 0), col="#555555", lwd=0.45)
        # Sparse y axis only in first sector to avoid clutter.
        if (sector == block_levels[1]) {
          at <- pretty(ylim, n=3)
          at <- at[at >= ylim[1] & at <= ylim[2]]
          circos.yaxis(side="left", at=at, labels=sprintf("%.1f", at),
                       labels.cex=0.34, tick.length=mm_x(0.7), lwd=0.35)
          circos.text(CELL_META$xlim[1] - mm_x(3.5), mean(ylim), track_title,
                      facing="inside", niceFacing=FALSE, cex=0.48, font=2,
                      adj=c(0.5, 0.5), col="#333333")
        }
      }
    )
  }

  # Outermost to innermost score tracks.
  draw_bar_track("Rstar", rstar_ylim, col_rstar, "R*")
  draw_bar_track("NES_risk", risk_ylim, col_risk, "NES risk")
  draw_bar_track("NES_protective", prot_ylim, col_prot, "NES protective")

  # Inner cohort labels and simple legend text.
  circos.trackPlotRegion(
    ylim=c(0, 1), track.height=0.06, bg.border=NA,
    panel.fun=function(x, y) {
      sector <- CELL_META$sector.index
      circos.text(mean(CELL_META$xlim), 0.5, ifelse(grepl("^dlPFC", sector), "dlPFC", "SNpc"),
                  facing="bending.inside", niceFacing=TRUE, cex=0.65, font=2, col="#222222")
    }
  )

  # Cohort-level labels spanning two sectors. highlight.sector gives the title hierarchy.
  suppressWarnings({
    highlight.sector(block_levels[1:2], track.index=1, col=NA, border=NA,
                     text="dlPFC", cex=cohort_cex, font=2, text.col="#111111",
                     niceFacing=TRUE)
    highlight.sector(block_levels[3:4], track.index=1, col=NA, border=NA,
                     text="SNpc", cex=cohort_cex, font=2, text.col="#111111",
                     niceFacing=TRUE)
  })

  title("PD-only single-cell R* by sub-cell type (Expand2)", cex.main=1.0, line=-1)
  circos.clear()
}

pdf_file <- file.path(out_dir, paste0(prefix, ".pdf"))
png_file <- file.path(out_dir, paste0(prefix, ".png"))
message("[plot] ", pdf_file)
make_plot(function(file, width, height) pdf(file, width=width, height=height, useDingbats=FALSE), pdf_file)
message("[plot] ", png_file)
make_plot(function(file, width, height) png(file, width=width, height=height, units="in", res=450), png_file)

# Optional compact legend PDF using ComplexHeatmap if available.
legend_file <- file.path(out_dir, paste0(prefix, "_legend.pdf"))
if (requireNamespace("ComplexHeatmap", quietly=TRUE) && requireNamespace("grid", quietly=TRUE)) {
  message("[legend] ", legend_file)
  pdf(legend_file, width=5.5, height=2.0, useDingbats=FALSE)
  lgd <- ComplexHeatmap::packLegend(
    ComplexHeatmap::Legend(title="R*", col_fun=col_rstar, direction="horizontal"),
    ComplexHeatmap::Legend(title="NES risk", col_fun=col_risk, direction="horizontal"),
    ComplexHeatmap::Legend(title="NES protective", col_fun=col_prot, direction="horizontal"),
    direction="vertical"
  )
  grid::grid.newpage()
  ComplexHeatmap::draw(lgd, x=grid::unit(0.5, "npc"), y=grid::unit(0.5, "npc"), just=c("center", "center"))
  dev.off()
} else {
  message("[legend] ComplexHeatmap not installed; skipped legend PDF.")
}

message("[done]")
