#!/usr/bin/env python3
# Publication header
# Step: 04_network_model
# Purpose: !/usr/bin/env python3
# Inputs: /mnt/f/13_scMR_/_data/network/graph_learning_borzoi_mr/gwas_linked_regulatory_variant_contributions.tsv.gz; /mnt/f/13_scMR_/_data/network/graph_learning_borzoi_mr/step16_variant_gene_context_deconvolution; representative_variant_program_network_nodes.tsv; representative_variant_program_network_edges.tsv; step16_variant_gene_context_deconvolution_qc.txt; representative_variants_for_network.tsv; context_cscore_groups_used.tsv; step16_run_config.json
# Input schema: Schema: not fully inferable from script; known columns should be verified against upstream data dictionaries or script-level read statements.
# Outputs: representative_variant_program_network_nodes.tsv; representative_variant_program_network_edges.tsv; representative_variant_program_network.png; representative_variants_for_network.tsv; context_cscore_groups_used.tsv
# Output schema: Schema: not fully inferable from script; preserve existing output filenames and columns.
# How to run: from this script directory, run `python 16b_variant_gene_celltype_disease_deconvolution.py` unless a project-specific driver script documents otherwise.
# Dependencies: __future__, argparse, json, logging, math, matplotlib, networkx, numpy, pandas, pathlib, re, typing
# Notes: Added during publication code-cleaning. This header is documentation only and does not change scientific logic, thresholds, statistical methods, filtering rules, model parameters, random seeds, figure values, or output content.

"""Step 16: variant -> gene -> cell type / disease contribution deconvolution.

This script extends the previous variant contribution decomposition workflow to produce
context-specific tables for single-cell/pseudobulk RLS program activity.

Inputs are intentionally explicit. If an expected file or required column is missing,
the script raises a clear error instead of silently guessing.

Core workflow
-------------
1. Load an existing variant-gene contribution table, preferably generated by
   08_variant_contribution_decomposition.py:
       gwas_linked_regulatory_variant_contributions.tsv.gz
2. Load a cell-type/disease cscore table from Step14/Step15.
3. Aggregate cscore by cell_type and disease.
4. Compute context-specific contribution:
       context_signed_contribution = signed_variant_contribution * context_cscore
   and related normalized/ranked metrics.
5. Write a full variant -> gene -> cell_type/disease table.
6. Select representative variants and build a compact network-ready table/plot.

Notes
-----
- The input variant contribution table already contains the decomposition of predicted
  node beta into GWAS-linked regulatory variant contributions. This script does not
  recompute Borzoi deltas or LD weights unless you rerun Step08 upstream.
- Context specificity comes from observed cscore activity in a disease/cell type.
- If the cscore table contains one row per cell, the script aggregates robustly.
- If disease labels contain composite diagnoses separated by ||, ;, comma, or /,
  the script can expand them so one sample/cell contributes to multiple disease groups.
"""
from __future__ import annotations

import argparse
import json
import logging
import math
import re
from pathlib import Path
from typing import Iterable, Optional

import numpy as np
import pandas as pd


def add_publication_config_argument(parser):
    """Add optional shared-config metadata without changing existing defaults."""
    parser.add_argument(
        "--config",
        default=None,
        help="Optional path to 00_config/paths.yaml. Loaded for publication wrappers; existing hard-coded defaults are preserved.",
    )


def load_publication_config(config_path):
    """Load optional shared config. Returns {} when --config is omitted."""
    if not config_path:
        return {}
    try:
        import yaml
    except ImportError as exc:
        raise RuntimeError("Optional --config support requires PyYAML when --config is provided") from exc
    with open(config_path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception:  # pragma: no cover
    plt = None

try:
    import networkx as nx
except Exception:  # pragma: no cover
    nx = None

EPS = 1e-12

DEFAULT_VARIANT_CONTRIBUTION = Path(
    "/mnt/f/13_scMR_/_data/network/graph_learning_borzoi_mr/gwas_linked_regulatory_variant_contributions.tsv.gz"
)
DEFAULT_OUTDIR = Path(
    "/mnt/f/13_scMR_/_data/network/graph_learning_borzoi_mr/step16_variant_gene_context_deconvolution"
)

DISEASE_ABBR = {
    "normal": "CTRL",
    "control": "CTRL",
    "ctrl": "CTRL",
    "healthy": "CTRL",
    "healthy control": "CTRL",
    "parkinson disease": "PD",
    "parkinson's disease": "PD",
    "lewy body dementia": "LBD",
    "dementia": "Dem",
    "alzheimer disease": "AD",
    "alzheimer's disease": "AD",
    "amyotrophic lateral sclerosis": "ALS",
    "brain neoplasm": "BN",
    "frontotemporal dementia": "FTD",
    "normal pressure hydrocephalus": "NPH",
    "schizophrenia": "SZ",
    "progressive supranuclear palsy": "PSP",
    "head injury": "HI",
    "major depressive disorder": "MDD",
    "multiple sclerosis": "MS",
    "post-traumatic stress disorder": "PTSD",
    "post traumatic stress disorder": "PTSD",
    "tauopathy": "Tau",
    "vascular dementia": "VaD",
}


def setup_logging(outdir: Path) -> None:
    (outdir / "logs").mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(outdir / "logs" / "16_variant_gene_celltype_disease_deconvolution.log", mode="w"),
        ],
    )


def require_file(path: Path, label: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Required {label} file does not exist: {path}")


def require_columns(df: pd.DataFrame, cols: Iterable[str], label: str) -> None:
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise ValueError(
            f"Required columns missing from {label}: {missing}\n"
            f"Available columns: {list(df.columns)}"
        )


def read_table(path: Path) -> pd.DataFrame:
    suffixes = "".join(path.suffixes)
    if suffixes.endswith(".parquet"):
        return pd.read_parquet(path)
    if suffixes.endswith(".csv") or suffixes.endswith(".csv.gz"):
        return pd.read_csv(path)
    return pd.read_csv(path, sep="\t")


def clean_gene(x) -> str:
    if pd.isna(x):
        return ""
    return str(x).strip().upper()


def normalize_label(x) -> str:
    if pd.isna(x):
        return "unknown"
    s = str(x).strip()
    if not s or s.lower() in {"nan", "none", "null", "na"}:
        return "unknown"
    return s


def disease_abbr_one(x) -> str:
    s = normalize_label(x)
    key = s.lower().strip()
    if key in DISEASE_ABBR:
        return DISEASE_ABBR[key]
    # human-readable fallback: keep short alphanumeric initials for long labels
    words = re.findall(r"[A-Za-z0-9]+", s)
    if len(words) >= 3:
        return "".join(w[0].upper() for w in words[:4])
    return s.replace(" ", "_")


def split_composite_disease(x) -> list[str]:
    s = normalize_label(x)
    if s == "unknown":
        return [s]
    parts = [p.strip() for p in re.split(r"\s*(?:\|\||;|,|/)\s*", s) if p.strip()]
    return parts if parts else [s]


def choose_cscore_column(df: pd.DataFrame, requested: Optional[str], gene_set: str) -> str:
    if requested:
        if requested not in df.columns:
            raise ValueError(f"Requested cscore column not found: {requested}. Available columns: {list(df.columns)}")
        return requested
    candidates = [
        "cscore",
        f"gsva_{gene_set}_cscore",
        f"{gene_set}_cscore",
        "cell_cscore",
        "context_cscore",
    ]
    for c in candidates:
        if c in df.columns:
            return c
    # Step15 per-cell files may contain one cscore-like column only.
    cands = [c for c in df.columns if c.lower().endswith("cscore") or c.lower() == "cscore"]
    if len(cands) == 1:
        return cands[0]
    raise ValueError(
        "Could not identify cscore column. Provide --cscore-col explicitly. "
        f"Available columns: {list(df.columns)}"
    )


def load_context_scores(
    cscore_path: Path,
    gene_set: str,
    cscore_col: Optional[str],
    cell_type_col: str,
    disease_col: str,
    dataset_col: Optional[str],
    expand_composite_disease: bool,
    min_observations: int,
) -> pd.DataFrame:
    logging.info("Loading context cscore table: %s", cscore_path)
    df = read_table(cscore_path)
    if cell_type_col not in df.columns:
        # common Step15 alternatives
        for alt in ["fine_cell_type", "subclass", "author_cell_type", "celltype", "cell_type"]:
            if alt in df.columns:
                logging.warning("Using %s as cell type column because %s was not found", alt, cell_type_col)
                cell_type_col = alt
                break
    require_columns(df, [cell_type_col, disease_col], "context cscore table")
    score_col = choose_cscore_column(df, cscore_col, gene_set)

    keep = [cell_type_col, disease_col, score_col]
    if dataset_col and dataset_col in df.columns:
        keep.append(dataset_col)
    elif dataset_col:
        logging.warning("Requested dataset column %s not found; using dataset='unknown'", dataset_col)
    sub = df[keep].copy()
    sub = sub.rename(columns={cell_type_col: "cell_type", disease_col: "disease", score_col: "cscore"})
    if dataset_col and dataset_col in sub.columns:
        sub = sub.rename(columns={dataset_col: "dataset"})
    else:
        sub["dataset"] = "unknown"
    sub["cell_type"] = sub["cell_type"].map(normalize_label)
    sub["disease"] = sub["disease"].map(normalize_label)
    sub["cscore"] = pd.to_numeric(sub["cscore"], errors="coerce")
    sub = sub.dropna(subset=["cscore"])

    if expand_composite_disease:
        rows = []
        for row in sub.itertuples(index=False):
            for d in split_composite_disease(row.disease):
                rows.append({"dataset": row.dataset, "cell_type": row.cell_type, "disease": d, "cscore": row.cscore})
        sub = pd.DataFrame(rows)

    grouped = (
        sub.groupby(["dataset", "cell_type", "disease"], dropna=False)["cscore"]
        .agg(n_context_observations="count", context_cscore_mean="mean", context_cscore_median="median", context_cscore_std="std")
        .reset_index()
    )
    grouped = grouped[grouped["n_context_observations"] >= min_observations].copy()
    grouped["disease_abbr"] = grouped["disease"].map(disease_abbr_one)
    # Positive activity magnitude and signed activity are both useful.
    grouped["context_activity_weight"] = grouped["context_cscore_mean"]
    grouped["context_abs_activity_weight"] = grouped["context_cscore_mean"].abs()
    logging.info("Context groups retained: %d", len(grouped))
    if grouped.empty:
        raise RuntimeError("No context groups retained after cscore aggregation. Lower --min-context-observations or check cscore input.")
    return grouped


def load_variant_contributions(path: Path, min_direction_confidence: float, min_relative_contribution: float) -> pd.DataFrame:
    logging.info("Loading variant-gene contribution table: %s", path)
    df = read_table(path)
    required = ["gene", "reg_rsid", "gwas_rsid", "signed_variant_contribution", "relative_variant_contribution"]
    require_columns(df, required, "variant-gene contribution table")
    df = df.copy()
    df["gene"] = df["gene"].map(clean_gene)
    numeric_cols = [
        "signed_variant_contribution", "abs_variant_contribution", "relative_variant_contribution",
        "pred_beta", "direction_confidence", "rwr_pred_beta", "rwr_confidence", "union_beta",
        "gwas_beta", "gwas_pval", "r", "r2", "borzoi_mean_delta", "borzoi_mean_abs_delta",
        "borzoi_max_abs_delta", "borzoi_sum_abs_delta", "gwas_weight", "borzoi_weight",
        "variant_total_weight", "normalized_variant_weight", "top_borzoi_track_delta",
    ]
    for c in numeric_cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
    if "abs_variant_contribution" not in df.columns:
        df["abs_variant_contribution"] = df["signed_variant_contribution"].abs()
    if "variant_pred_direction" not in df.columns:
        df["variant_pred_direction"] = np.where(df["signed_variant_contribution"] > 0, "risk", np.where(df["signed_variant_contribution"] < 0, "protective", "neutral"))
    if "direction_confidence" in df.columns and min_direction_confidence > 0:
        before = len(df)
        df = df[df["direction_confidence"].fillna(0) >= min_direction_confidence].copy()
        logging.info("Filtered by direction_confidence >= %.3g: %d -> %d", min_direction_confidence, before, len(df))
    if min_relative_contribution > 0:
        before = len(df)
        df = df[df["relative_variant_contribution"].fillna(0) >= min_relative_contribution].copy()
        logging.info("Filtered by relative_variant_contribution >= %.3g: %d -> %d", min_relative_contribution, before, len(df))
    if df.empty:
        raise RuntimeError("No variant-gene contribution rows remain after filters.")
    logging.info("Variant-gene rows loaded: %d; genes=%d; regulatory variants=%d", len(df), df.gene.nunique(), df.reg_rsid.nunique())
    return df


def build_context_deconvolution(variant_df: pd.DataFrame, context_df: pd.DataFrame) -> pd.DataFrame:
    logging.info("Building full variant -> gene -> cell type/disease deconvolution table")
    # Cross join: each variant-gene contribution is contextualized by each observed cell_type/disease cscore group.
    left = variant_df.copy()
    right = context_df.copy()
    left["_k"] = 1
    right["_k"] = 1
    full = left.merge(right, on="_k", how="inner").drop(columns="_k")

    full["context_signed_contribution"] = (
        pd.to_numeric(full["signed_variant_contribution"], errors="coerce").fillna(0)
        * pd.to_numeric(full["context_activity_weight"], errors="coerce").fillna(0)
    )
    full["context_abs_contribution"] = full["context_signed_contribution"].abs()
    full["context_direction"] = np.where(
        full["context_signed_contribution"] > 0,
        "risk",
        np.where(full["context_signed_contribution"] < 0, "protective", "neutral"),
    )

    # Normalize within each dataset/cell_type/disease so the table is interpretable as contribution share.
    grp = ["dataset", "cell_type", "disease"]
    total_abs = full.groupby(grp)["context_abs_contribution"].transform("sum")
    full["context_relative_contribution"] = np.where(total_abs > 0, full["context_abs_contribution"] / (total_abs + EPS), 0.0)
    full["context_rank_abs"] = full.groupby(grp)["context_abs_contribution"].rank(method="first", ascending=False).astype(int)

    gene_abs = full.groupby(grp + ["gene"])["context_abs_contribution"].transform("sum")
    gene_total = full.groupby(grp)["context_abs_contribution"].transform("sum")
    full["gene_context_relative_contribution"] = np.where(gene_total > 0, gene_abs / (gene_total + EPS), 0.0)

    return full


def aggregate_tables(full: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    logging.info("Building aggregate tables")
    common = ["dataset", "cell_type", "disease", "disease_abbr"]

    gene = (
        full.groupby(common + ["gene"], dropna=False)
        .agg(
            n_variant_gene_rows=("gene", "size"),
            n_regulatory_variants=("reg_rsid", "nunique"),
            n_gwas_variants=("gwas_rsid", "nunique"),
            context_signed_gene_contribution=("context_signed_contribution", "sum"),
            context_abs_gene_contribution=("context_abs_contribution", "sum"),
            mean_context_cscore=("context_cscore_mean", "first"),
            max_variant_relative_contribution=("context_relative_contribution", "max"),
            pred_beta=("pred_beta", "first") if "pred_beta" in full.columns else ("context_signed_contribution", "sum"),
            pred_direction=("pred_direction", "first") if "pred_direction" in full.columns else ("context_direction", "first"),
            direction_confidence=("direction_confidence", "first") if "direction_confidence" in full.columns else ("context_abs_contribution", "mean"),
        )
        .reset_index()
    )
    total_abs = gene.groupby(common)["context_abs_gene_contribution"].transform("sum")
    gene["context_relative_gene_contribution"] = np.where(total_abs > 0, gene["context_abs_gene_contribution"] / (total_abs + EPS), 0.0)
    gene["gene_rank_abs"] = gene.groupby(common)["context_abs_gene_contribution"].rank(method="first", ascending=False).astype(int)

    variant_gene = (
        full.groupby(common + ["reg_rsid", "gwas_rsid", "gene"], dropna=False)
        .agg(
            n_rows=("gene", "size"),
            context_signed_contribution=("context_signed_contribution", "sum"),
            context_abs_contribution=("context_abs_contribution", "sum"),
            context_relative_contribution=("context_relative_contribution", "sum"),
            signed_variant_contribution=("signed_variant_contribution", "first"),
            relative_variant_contribution=("relative_variant_contribution", "first"),
            variant_pred_direction=("variant_pred_direction", "first"),
            directional_support_class=("directional_support_class", "first") if "directional_support_class" in full.columns else ("context_direction", "first"),
            dhs_identifier=("dhs_identifier", "first") if "dhs_identifier" in full.columns else ("gene", "first"),
            dhs_tissue=("dhs_tissue", "first") if "dhs_tissue" in full.columns else ("gene", "first"),
            top_borzoi_track=("top_borzoi_track", "first") if "top_borzoi_track" in full.columns else ("gene", "first"),
            borzoi_mean_delta=("borzoi_mean_delta", "first") if "borzoi_mean_delta" in full.columns else ("context_signed_contribution", "sum"),
            gwas_beta=("gwas_beta", "first") if "gwas_beta" in full.columns else ("context_signed_contribution", "sum"),
            gwas_pval=("gwas_pval", "first") if "gwas_pval" in full.columns else ("context_signed_contribution", "sum"),
            r2=("r2", "first") if "r2" in full.columns else ("context_signed_contribution", "sum"),
        )
        .reset_index()
    )
    variant_gene["context_rank_abs"] = variant_gene.groupby(common)["context_abs_contribution"].rank(method="first", ascending=False).astype(int)

    if "dhs_identifier" in full.columns:
        dhs = (
            full.groupby(common + ["dhs_identifier"], dropna=False)
            .agg(
                n_genes=("gene", "nunique"),
                n_regulatory_variants=("reg_rsid", "nunique"),
                n_gwas_variants=("gwas_rsid", "nunique"),
                context_signed_dhs_contribution=("context_signed_contribution", "sum"),
                context_abs_dhs_contribution=("context_abs_contribution", "sum"),
                top_dhs_tissue=("dhs_tissue", "first") if "dhs_tissue" in full.columns else ("gene", "first"),
            )
            .reset_index()
        )
        total_dhs = dhs.groupby(common)["context_abs_dhs_contribution"].transform("sum")
        dhs["context_relative_dhs_contribution"] = np.where(total_dhs > 0, dhs["context_abs_dhs_contribution"] / (total_dhs + EPS), 0.0)
        dhs["dhs_rank_abs"] = dhs.groupby(common)["context_abs_dhs_contribution"].rank(method="first", ascending=False).astype(int)
    else:
        dhs = pd.DataFrame()

    return gene, variant_gene, dhs


def select_representative_variants(
    variant_gene: pd.DataFrame,
    top_n_per_context: int,
    max_total: int,
    require_concordant: bool,
) -> pd.DataFrame:
    logging.info("Selecting representative variants")
    df = variant_gene.copy()
    if require_concordant and "directional_support_class" in df.columns:
        df = df[df["directional_support_class"].isin(["concordant", "unresolved"])].copy()
    df = df.sort_values(
        ["dataset", "cell_type", "disease", "context_abs_contribution", "context_relative_contribution"],
        ascending=[True, True, True, False, False],
    )
    reps = df.groupby(["dataset", "cell_type", "disease"], group_keys=False).head(top_n_per_context).copy()
    reps = reps.sort_values("context_abs_contribution", ascending=False).head(max_total).reset_index(drop=True)
    reps["representative_rank_global"] = np.arange(1, len(reps) + 1)
    return reps


def make_network_tables(reps: pd.DataFrame, gene_summary: pd.DataFrame, outdir: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    logging.info("Building representative-variant network node/edge tables")
    node_rows = []
    edge_rows = []

    # Context nodes.
    for ctx in reps[["dataset", "cell_type", "disease", "disease_abbr"]].drop_duplicates().itertuples(index=False):
        cid = f"CTX::{ctx.dataset}::{ctx.cell_type}::{ctx.disease_abbr}"
        node_rows.append({
            "node_id": cid,
            "node_label": f"{ctx.cell_type}\n{ctx.disease_abbr}",
            "node_type": "celltype_disease_context",
            "dataset": ctx.dataset,
            "cell_type": ctx.cell_type,
            "disease": ctx.disease,
            "disease_abbr": ctx.disease_abbr,
        })

    for row in reps.itertuples(index=False):
        ctx_id = f"CTX::{row.dataset}::{row.cell_type}::{row.disease_abbr}"
        v_id = f"VAR::{row.reg_rsid}"
        g_id = f"GENE::{row.gene}"
        node_rows.append({
            "node_id": v_id,
            "node_label": str(row.reg_rsid),
            "node_type": "regulatory_variant",
            "dataset": row.dataset,
            "cell_type": row.cell_type,
            "disease": row.disease,
            "disease_abbr": row.disease_abbr,
        })
        node_rows.append({
            "node_id": g_id,
            "node_label": str(row.gene),
            "node_type": "target_gene",
            "dataset": row.dataset,
            "cell_type": row.cell_type,
            "disease": row.disease,
            "disease_abbr": row.disease_abbr,
        })
        edge_rows.append({
            "source": v_id,
            "target": g_id,
            "edge_type": "variant_to_gene_regulatory_contribution",
            "weight": row.context_abs_contribution,
            "signed_weight": row.context_signed_contribution,
            "direction": "risk" if row.context_signed_contribution > 0 else "protective" if row.context_signed_contribution < 0 else "neutral",
            "dataset": row.dataset,
            "cell_type": row.cell_type,
            "disease": row.disease,
            "disease_abbr": row.disease_abbr,
            "reg_rsid": row.reg_rsid,
            "gwas_rsid": row.gwas_rsid,
            "gene": row.gene,
        })
        edge_rows.append({
            "source": g_id,
            "target": ctx_id,
            "edge_type": "gene_to_active_celltype_disease_program",
            "weight": row.context_abs_contribution,
            "signed_weight": row.context_signed_contribution,
            "direction": "risk" if row.context_signed_contribution > 0 else "protective" if row.context_signed_contribution < 0 else "neutral",
            "dataset": row.dataset,
            "cell_type": row.cell_type,
            "disease": row.disease,
            "disease_abbr": row.disease_abbr,
            "reg_rsid": row.reg_rsid,
            "gwas_rsid": row.gwas_rsid,
            "gene": row.gene,
        })

    nodes = pd.DataFrame(node_rows).drop_duplicates("node_id")
    edges = pd.DataFrame(edge_rows)
    nodes.to_csv(outdir / "representative_variant_program_network_nodes.tsv", sep="\t", index=False)
    edges.to_csv(outdir / "representative_variant_program_network_edges.tsv", sep="\t", index=False)
    return nodes, edges


def plot_representative_network(nodes: pd.DataFrame, edges: pd.DataFrame, outdir: Path, max_edges: int) -> None:
    if nx is None or plt is None:
        logging.warning("networkx/matplotlib unavailable; skipping representative network plot")
        return
    if edges.empty or nodes.empty:
        logging.warning("No network nodes/edges; skipping plot")
        return
    e = edges.sort_values("weight", ascending=False).head(max_edges).copy()
    used_nodes = set(e["source"]).union(set(e["target"]))
    n = nodes[nodes["node_id"].isin(used_nodes)].copy()

    G = nx.DiGraph()
    for row in n.itertuples(index=False):
        G.add_node(row.node_id, label=row.node_label, node_type=row.node_type)
    for row in e.itertuples(index=False):
        if row.source in G and row.target in G:
            G.add_edge(row.source, row.target, weight=float(row.weight), signed_weight=float(row.signed_weight), edge_type=row.edge_type)

    if G.number_of_nodes() == 0:
        return
    fig_w = max(10, min(22, 0.35 * G.number_of_nodes() + 8))
    fig_h = max(8, min(18, 0.25 * G.number_of_nodes() + 6))
    plt.figure(figsize=(fig_w, fig_h))
    pos = nx.spring_layout(G, seed=42, k=1.2 / math.sqrt(max(G.number_of_nodes(), 1)))
    labels = nx.get_node_attributes(G, "label")
    node_types = nx.get_node_attributes(G, "node_type")
    sizes = []
    for node in G.nodes:
        deg_w = sum(abs(G[u][v].get("weight", 0)) for u, v in G.in_edges(node)) + sum(abs(G[u][v].get("weight", 0)) for u, v in G.out_edges(node))
        base = 800 if node_types.get(node) == "celltype_disease_context" else 600 if node_types.get(node) == "target_gene" else 350
        sizes.append(base + 2500 * deg_w / (e["weight"].max() + EPS))
    nx.draw_networkx_edges(G, pos, arrows=True, alpha=0.35, width=[1 + 3 * G[u][v]["weight"] / (e["weight"].max() + EPS) for u, v in G.edges])
    nx.draw_networkx_nodes(G, pos, node_size=sizes, alpha=0.85)
    nx.draw_networkx_labels(G, pos, labels=labels, font_size=8)
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(outdir / "representative_variant_program_network.png", dpi=220)
    plt.close()


def write_qc(outdir: Path, args: argparse.Namespace, variant_df: pd.DataFrame, context_df: pd.DataFrame, full: pd.DataFrame, reps: pd.DataFrame) -> None:
    lines = [
        f"variant_contribution_file\t{args.variant_contribution_file}",
        f"context_cscore_file\t{args.context_cscore_file}",
        f"gene_set\t{args.gene_set}",
        f"variant_gene_rows_loaded\t{len(variant_df)}",
        f"unique_genes_loaded\t{variant_df.gene.nunique()}",
        f"unique_regulatory_variants_loaded\t{variant_df.reg_rsid.nunique()}",
        f"context_groups\t{len(context_df)}",
        f"full_deconvolution_rows\t{len(full)}",
        f"representative_variant_rows\t{len(reps)}",
        f"min_direction_confidence\t{args.min_direction_confidence}",
        f"min_relative_contribution\t{args.min_relative_contribution}",
        f"min_context_observations\t{args.min_context_observations}",
        "top_20_representative_variants",
    ]
    if len(reps):
        cols = ["dataset", "cell_type", "disease_abbr", "reg_rsid", "gwas_rsid", "gene", "context_abs_contribution", "context_relative_contribution", "context_signed_contribution"]
        lines.append(reps[[c for c in cols if c in reps.columns]].head(20).to_string(index=False))
    else:
        lines.append("NA")
    (outdir / "step16_variant_gene_context_deconvolution_qc.txt").write_text("\n".join(lines) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description="Step16 variant -> gene -> cell type/disease contribution deconvolution")
    add_publication_config_argument(ap)
    ap.add_argument("--variant-contribution-file", type=Path, default=DEFAULT_VARIANT_CONTRIBUTION,
                    help="Output from 08_variant_contribution_decomposition.py, usually gwas_linked_regulatory_variant_contributions.tsv.gz")
    ap.add_argument("--context-cscore-file", type=Path, required=True,
                    help="Step14/Step15 cscore table with cell_type, disease and cscore columns. TSV/CSV/Parquet supported.")
    ap.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    ap.add_argument("--gene-set", default="brain_expanded_merged")
    ap.add_argument("--cscore-col", default=None, help="Explicit cscore column if auto-detection is not desired")
    ap.add_argument("--cell-type-col", default="cell_type")
    ap.add_argument("--disease-col", default="disease")
    ap.add_argument("--dataset-col", default="dataset")
    ap.add_argument("--no-expand-composite-disease", action="store_true",
                    help="Do not split composite disease strings such as 'dementia||AD||LBD'")
    ap.add_argument("--min-context-observations", type=int, default=1,
                    help="Minimum number of cells/samples per dataset/cell_type/disease context")
    ap.add_argument("--min-direction-confidence", type=float, default=0.0,
                    help="Optional filter on model direction confidence")
    ap.add_argument("--min-relative-contribution", type=float, default=0.0,
                    help="Optional filter on gene-level relative variant contribution")
    ap.add_argument("--top-n-representative-per-context", type=int, default=10)
    ap.add_argument("--max-representative-total", type=int, default=300)
    ap.add_argument("--require-concordant-representatives", action="store_true",
                    help="For representative network, keep concordant/unresolved but not discordant variant-gene rows")
    ap.add_argument("--network-max-edges", type=int, default=250)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    args._publication_config = load_publication_config(args.config)

    args.outdir.mkdir(parents=True, exist_ok=True)
    setup_logging(args.outdir)
    require_file(args.variant_contribution_file, "variant contribution")
    require_file(args.context_cscore_file, "context cscore")

    full_out = args.outdir / "variant_gene_celltype_disease_deconvolution_full.tsv.gz"
    gene_out = args.outdir / "gene_context_deconvolution_summary.tsv.gz"
    vg_out = args.outdir / "variant_gene_context_deconvolution_summary.tsv.gz"
    dhs_out = args.outdir / "dhs_context_deconvolution_summary.tsv.gz"
    reps_out = args.outdir / "representative_variants_for_network.tsv"
    if full_out.exists() and gene_out.exists() and vg_out.exists() and reps_out.exists() and not args.force:
        logging.info("Step16 outputs already exist. Use --force to recompute.")
        return

    variant_df = load_variant_contributions(
        args.variant_contribution_file,
        min_direction_confidence=args.min_direction_confidence,
        min_relative_contribution=args.min_relative_contribution,
    )
    context_df = load_context_scores(
        args.context_cscore_file,
        gene_set=args.gene_set,
        cscore_col=args.cscore_col,
        cell_type_col=args.cell_type_col,
        disease_col=args.disease_col,
        dataset_col=args.dataset_col,
        expand_composite_disease=not args.no_expand_composite_disease,
        min_observations=args.min_context_observations,
    )
    context_df.to_csv(args.outdir / "context_cscore_groups_used.tsv", sep="\t", index=False)

    full = build_context_deconvolution(variant_df, context_df)
    gene, variant_gene, dhs = aggregate_tables(full)
    reps = select_representative_variants(
        variant_gene,
        top_n_per_context=args.top_n_representative_per_context,
        max_total=args.max_representative_total,
        require_concordant=args.require_concordant_representatives,
    )
    nodes, edges = make_network_tables(reps, gene, args.outdir)
    plot_representative_network(nodes, edges, args.outdir, max_edges=args.network_max_edges)

    # Keep column order stable but do not drop available evidence columns.
    priority_cols = [
        "dataset", "cell_type", "disease", "disease_abbr", "context_cscore_mean", "context_cscore_median", "n_context_observations",
        "gene", "reg_rsid", "gwas_rsid", "variant_pred_direction", "context_direction",
        "context_signed_contribution", "context_abs_contribution", "context_relative_contribution", "context_rank_abs",
        "signed_variant_contribution", "relative_variant_contribution", "pred_beta", "pred_direction", "direction_confidence",
        "dhs_identifier", "dhs_tissue", "gwas_beta", "gwas_pval", "r", "r2",
        "borzoi_mean_delta", "borzoi_mean_abs_delta", "top_borzoi_track", "top_borzoi_track_delta",
        "directional_support_class", "contribution_class",
    ]
    ordered = [c for c in priority_cols if c in full.columns] + [c for c in full.columns if c not in priority_cols]
    full[ordered].to_csv(full_out, sep="\t", index=False, compression="gzip")
    gene.to_csv(gene_out, sep="\t", index=False, compression="gzip")
    variant_gene.to_csv(vg_out, sep="\t", index=False, compression="gzip")
    if not dhs.empty:
        dhs.to_csv(dhs_out, sep="\t", index=False, compression="gzip")
    reps.to_csv(reps_out, sep="\t", index=False)

    with open(args.outdir / "step16_run_config.json", "w") as fh:
        json.dump({k: str(v) if isinstance(v, Path) else v for k, v in vars(args).items()}, fh, indent=2)
    write_qc(args.outdir, args, variant_df, context_df, full, reps)

    logging.info("Wrote full deconvolution table: %s rows=%d", full_out, len(full))
    logging.info("Wrote gene summary: %s rows=%d", gene_out, len(gene))
    logging.info("Wrote variant-gene summary: %s rows=%d", vg_out, len(variant_gene))
    logging.info("Wrote representative variants/network outputs to: %s", args.outdir)


if __name__ == "__main__":
    main()
