#!/usr/bin/env python3
# Publication header
# Step: 05_gsva_analysis
# Purpose: !/usr/bin/env python3
# Inputs: /mnt/f/0.datasets/cellxgene/MSSM_Cohort_split_by_subclass; /mnt/f/13_scMR_/_data/analysis_borzoi_mr_sc/; bulk_gsva_brain_model_gene_sets/brain_mr_model_gene_sets.tsv; singlecell_gsva_brain_model_gene_sets/step15d_balanced_global_gsva_mssm; *.h5ad; mssm_balanced_gene_qc.tsv; mssm_balanced_expression_genes.tsv; step15d_prepare_balanced_expression_config.json
# Input schema: Schema: not fully inferable from script; known columns should be verified against upstream data dictionaries or script-level read statements.
# Outputs: bulk_gsva_brain_model_gene_sets/brain_mr_model_gene_sets.tsv; mssm_balanced_gene_qc.tsv; mssm_balanced_expression_genes.tsv
# Output schema: Schema: not fully inferable from script; preserve existing output filenames and columns.
# How to run: from this script directory, run `python 15d_prepare_balanced_mssm_expression.py` unless a project-specific driver script documents otherwise.
# Dependencies: __future__, anndata, argparse, gc, gzip, json, math, numpy, pandas, pathlib, re, scipy, sys, tqdm, typing
# Notes: Added during publication code-cleaning. This header is documentation only and does not change scientific logic, thresholds, statistical methods, filtering rules, model parameters, random seeds, figure values, or output content.

"""
Step 15d. Build a QC-passed, balanced MSSM single-cell expression matrix for
one global GSVA run.

Purpose
-------
This script is intended to replace split-wise per-cell GSVA for MSSM. It:
  1. reads MSSM split .h5ad files generated by Step 15a,
  2. restricts expression features to PPI-network genes,
  3. applies per-cell sparsity QC using minimum detected feature fraction,
  4. samples up to N QC-passed cells per cell type, balanced across diseases,
  5. writes a balanced expression table suitable for one global R/GSVA call.

Default QC requested in discussion:
  detected PPI-network feature fraction > 20%
  up to 10,000 QC-passed cells per cell type

Important
---------
The output expression table is genes x cells, because GSVA expects genes as
rows and samples/cells as columns.

For very large PPI gene universes and many sampled cells, the TSV can be large.
The script writes a cell x gene float32 memmap internally first, then streams a
genes x cells TSV.gz.
"""

from __future__ import annotations

import argparse
import gc
import gzip
import json
import math
import re
import sys
from pathlib import Path
from typing import Optional

import anndata as ad
import numpy as np
import pandas as pd
import scipy.sparse as sp
from tqdm import tqdm


def add_publication_config_argument(parser):
    """Add optional shared-config metadata without changing existing defaults."""
    parser.add_argument(
        "--config",
        default=None,
        help="Optional path to 00_config/paths.yaml. Loaded for publication wrappers; existing hard-coded defaults are preserved.",
    )


def load_publication_config(config_path):
    """Load optional shared config. Returns {} when --config is omitted."""
    if not config_path:
        return {}
    try:
        import yaml
    except ImportError as exc:
        raise RuntimeError("Optional --config support requires PyYAML when --config is provided") from exc
    with open(config_path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


DEFAULT_SPLIT_DIR = Path("/mnt/f/0.datasets/cellxgene/MSSM_Cohort_split_by_subclass")
DEFAULT_GENE_SET_FILE = Path(
    "/mnt/f/13_scMR_/_data/analysis_borzoi_mr_sc/"
    "bulk_gsva_brain_model_gene_sets/brain_mr_model_gene_sets.tsv"
)
DEFAULT_OUTDIR = Path(
    "/mnt/f/13_scMR_/_data/analysis_borzoi_mr_sc/"
    "singlecell_gsva_brain_model_gene_sets/step15d_balanced_global_gsva_mssm"
)

DISEASE_ABBR = {
    "normal": "CTRL", "control": "CTRL", "ctrl": "CTRL", "healthy": "CTRL", "healthy control": "CTRL",
    "parkinson disease": "PD", "parkinson's disease": "PD",
    "lewy body dementia": "LBD", "dementia": "Dem",
    "alzheimer disease": "AD", "alzheimer's disease": "AD",
    "amyotrophic lateral sclerosis": "ALS", "brain neoplasm": "BN",
    "frontotemporal dementia": "FTD", "normal pressure hydrocephalus": "NPH",
    "schizophrenia": "SZ", "progressive supranuclear palsy": "PSP",
    "head injury": "HI", "major depressive disorder": "MDD",
    "multiple sclerosis": "MS", "post-traumatic stress disorder": "PTSD",
    "post traumatic stress disorder": "PTSD", "tauopathy": "Tau", "vascular dementia": "VaD",
}


def clean_label(x: object) -> str:
    if pd.isna(x):
        return "unknown"
    s = str(x).strip()
    if not s or s.lower() in {"nan", "na", "none", "null"}:
        return "unknown"
    return s


def standardize_gene_symbol(x: object) -> Optional[str]:
    if pd.isna(x):
        return None
    s = str(x).strip()
    if not s or s.lower() in {"nan", "na", "none", "null"}:
        return None
    return s.upper()


def split_disease_components(x: object) -> list[str]:
    s = clean_label(x)
    parts = [p.strip() for p in re.split(r"\s*(?:\|\||;|,|/)\s*", s) if p.strip()]
    return parts if parts else ["unknown"]


def disease_to_abbr_component(x: object) -> str:
    key = re.sub(r"\s+", " ", clean_label(x).lower()).strip()
    return DISEASE_ABBR.get(key, clean_label(x))


def disease_to_abbr(x: object) -> str:
    return "+".join(disease_to_abbr_component(p) for p in split_disease_components(x))


def make_safe(x: object) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(x)).strip("_") or "unknown"


def find_h5ad_files(split_dir: Path, manifest: Optional[Path], pattern: str) -> list[Path]:
    if manifest is not None:
        man = pd.read_csv(manifest, sep="\t")
        for c in ["path", "h5ad_path", "output_path", "file"]:
            if c in man.columns:
                paths = [Path(x) for x in man[c].dropna().astype(str)]
                return [p for p in paths if p.exists()]
        raise SystemExit(f"Manifest has no recognized path column: {manifest}")
    files = sorted(split_dir.glob(pattern))
    if not files:
        files = sorted(split_dir.rglob(pattern))
    return [p for p in files if p.exists()]


def load_gene_sets(path: Path, gene_set: str) -> tuple[set[str], set[str], pd.DataFrame]:
    gs = pd.read_csv(path, sep="\t")
    required = {"gene_set", "gene", "direction"}
    missing = required - set(gs.columns)
    if missing:
        raise SystemExit(f"Gene set file missing columns: {sorted(missing)}")
    gs = gs.copy()
    gs["gene"] = gs["gene"].map(standardize_gene_symbol)
    gs["gene_set"] = gs["gene_set"].astype(str).str.strip()
    gs["direction"] = gs["direction"].astype(str).str.lower().str.strip()
    gs = gs.dropna(subset=["gene"])
    sub = gs[gs["gene_set"].eq(gene_set)].copy()
    if sub.empty:
        raise SystemExit(f"No genes found for gene_set={gene_set} in {path}")
    risk = set(sub.loc[sub["direction"].eq("risk"), "gene"])
    protective = set(sub.loc[sub["direction"].eq("protective"), "gene"])
    if not risk or not protective:
        raise SystemExit(f"Need both risk and protective genes for {gene_set}. risk={len(risk)}, protective={len(protective)}")
    return risk, protective, sub


def load_gene_list(path: Optional[Path], column: Optional[str]) -> Optional[set[str]]:
    if path is None:
        return None
    if not path.exists():
        raise SystemExit(f"Missing gene list file: {path}")
    if path.suffix.lower() in {".txt", ".list"}:
        vals = [x.strip() for x in path.read_text().splitlines() if x.strip()]
        return {g for g in map(standardize_gene_symbol, vals) if g}
    df = pd.read_csv(path, sep=None, engine="python")
    if column and column in df.columns:
        col = column
    else:
        candidates = ["gene", "symbol", "gene_symbol", "Gene", "gene_u", "gene_v" ]
        col = next((c for c in candidates if c in df.columns), df.columns[0])
    return {g for g in df[col].map(standardize_gene_symbol).dropna().unique() if g}


def get_var_gene_names(adata: ad.AnnData) -> np.ndarray:
    if "feature_name" in adata.var.columns:
        names = adata.var["feature_name"].astype(str).values
    elif "gene_name" in adata.var.columns:
        names = adata.var["gene_name"].astype(str).values
    else:
        names = adata.var_names.astype(str).values
    return np.array([standardize_gene_symbol(x) for x in names], dtype=object)


def pick_obs_col(obs: pd.DataFrame, requested: Optional[str], candidates: list[str], default: str = "unknown") -> tuple[Optional[str], pd.Series]:
    if requested and requested in obs.columns:
        return requested, obs[requested].astype(str)
    for c in candidates:
        if c in obs.columns:
            return c, obs[c].astype(str)
    return None, pd.Series([default] * len(obs), index=obs.index, dtype="object")


def subset_X(adata: ad.AnnData, row_idx: np.ndarray, gene_idx: np.ndarray):
    X = adata.X[row_idx, :]
    X = X[:, gene_idx]
    if sp.issparse(X):
        return X.tocsr()
    return np.asarray(X)


def detection_and_sum(X) -> tuple[np.ndarray, np.ndarray]:
    if sp.issparse(X):
        n_detected = np.asarray(X.getnnz(axis=1)).ravel()
        total = np.asarray(X.sum(axis=1)).ravel()
    else:
        n_detected = np.count_nonzero(X > 0, axis=1)
        total = np.asarray(X.sum(axis=1)).ravel()
    return n_detected.astype(np.int32), total.astype(np.float64)


def first_pass_qc(
    files: list[Path],
    selected_genes: set[str],
    args: argparse.Namespace,
) -> tuple[pd.DataFrame, list[str], dict[str, list[int]]]:
    qc_frames = []
    file_gene_indices: dict[str, list[int]] = {}
    common_genes: Optional[list[str]] = None

    for file_i, path in enumerate(files, start=1):
        print(f"[QC {file_i}/{len(files)}] {path}")
        adata = ad.read_h5ad(path, backed="r")
        try:
            gene_names = get_var_gene_names(adata)
            gene_to_idx = {}
            for i, g in enumerate(gene_names):
                if g and g not in gene_to_idx:
                    gene_to_idx[g] = i
            genes_present = sorted(selected_genes & set(gene_to_idx))
            if not genes_present:
                print(f"  [WARN] no selected genes found in {path.name}; skipped")
                continue
            gene_idx = np.array([gene_to_idx[g] for g in genes_present], dtype=np.int64)
            file_gene_indices[str(path)] = gene_idx.tolist()
            if common_genes is None:
                common_genes = genes_present
            else:
                # Keep the intersection across all files already seen to avoid mismatched matrix rows.
                common_genes = sorted(set(common_genes) & set(genes_present))

            obs = adata.obs.copy()
            _, cell_type = pick_obs_col(obs, args.cell_type_col, ["subclass", "cell_type", "author_cell_type", "fine_cell_type"])
            _, fine_cell_type = pick_obs_col(obs, args.fine_cell_type_col, ["subclass", "author_cell_type", "cell_type"])
            _, disease = pick_obs_col(obs, args.disease_col, ["disease", "diagnosis", "condition"])
            _, donor = pick_obs_col(obs, args.donor_col, ["donor_id", "individual", "patient", "sample", "sample_id", "orig.ident"])

            umap_cols = []
            for a, b in [("umap_1", "umap_2"), ("UMAP_1", "UMAP_2"), ("X_umap_1", "X_umap_2")]:
                if a in obs.columns and b in obs.columns:
                    umap_cols = [a, b]
                    break
            has_obsm_umap = "X_umap" in adata.obsm.keys()

            n = adata.n_obs
            kept_parts = []
            for start in tqdm(range(0, n, args.chunk_size), desc=path.stem, unit="chunk", dynamic_ncols=True):
                end = min(start + args.chunk_size, n)
                rows = np.arange(start, end, dtype=np.int64)
                X = subset_X(adata, rows, gene_idx)
                n_detected, total_counts = detection_and_sum(X)
                detected_fraction = n_detected / max(1, len(gene_idx))
                keep = detected_fraction > args.min_detected_fraction
                if not np.any(keep):
                    continue
                local_rows = rows[keep]
                part = pd.DataFrame({
                    "source_h5ad": str(path),
                    "source_file": path.stem,
                    "local_index": local_rows,
                    "cell_id": adata.obs_names[local_rows].astype(str).values,
                    "cell_type": cell_type.iloc[local_rows].map(clean_label).values,
                    "fine_cell_type": fine_cell_type.iloc[local_rows].map(clean_label).values,
                    "disease": disease.iloc[local_rows].map(clean_label).values,
                    "disease_abbr": [disease_to_abbr(x) for x in disease.iloc[local_rows].values],
                    "donor_id": donor.iloc[local_rows].map(clean_label).values,
                    "n_detected_selected": n_detected[keep],
                    "total_counts_selected": total_counts[keep],
                    "detected_fraction_selected": detected_fraction[keep],
                })
                if umap_cols:
                    part["umap_1"] = pd.to_numeric(obs.iloc[local_rows][umap_cols[0]], errors="coerce").values
                    part["umap_2"] = pd.to_numeric(obs.iloc[local_rows][umap_cols[1]], errors="coerce").values
                elif has_obsm_umap:
                    coords = np.asarray(adata.obsm["X_umap"][local_rows, :])
                    part["umap_1"] = coords[:, 0]
                    part["umap_2"] = coords[:, 1]
                else:
                    part["umap_1"] = np.nan
                    part["umap_2"] = np.nan
                kept_parts.append(part)
                del X
            if kept_parts:
                qc_frames.append(pd.concat(kept_parts, ignore_index=True))
                print(f"  QC-passed cells: {sum(len(x) for x in kept_parts):,}")
        finally:
            adata.file.close()
            del adata
            gc.collect()

    if not qc_frames:
        raise SystemExit("No QC-passed cells found")
    if not common_genes:
        raise SystemExit("No common selected genes found across split files")
    qc = pd.concat(qc_frames, ignore_index=True)
    qc["balanced_cell_id"] = [f"MSSM__{make_safe(sf)}__{make_safe(cid)}" for sf, cid in zip(qc["source_file"], qc["cell_id"])]
    return qc, common_genes, file_gene_indices


def balanced_sample(qc: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    rng = np.random.default_rng(args.seed)
    pieces = []
    for cell_type, sub_ct in qc.groupby("cell_type", dropna=False):
        max_ct = args.max_cells_per_cell_type
        if max_ct <= 0 or len(sub_ct) <= max_ct:
            pieces.append(sub_ct)
            continue
        group_col = args.balance_group_col
        groups = list(sub_ct.groupby(group_col, dropna=False))
        per_group = max(1, int(math.floor(max_ct / max(1, len(groups)))))
        chosen_idx = []
        leftovers = []
        for _, sub_g in groups:
            idx = sub_g.index.to_numpy()
            if len(idx) <= per_group:
                chosen_idx.extend(idx.tolist())
            else:
                chosen = rng.choice(idx, size=per_group, replace=False)
                chosen_idx.extend(chosen.tolist())
                leftovers.extend([x for x in idx if x not in set(chosen)])
        remaining = max_ct - len(chosen_idx)
        if remaining > 0 and leftovers:
            extra = rng.choice(np.array(leftovers), size=min(remaining, len(leftovers)), replace=False)
            chosen_idx.extend(extra.tolist())
        pieces.append(qc.loc[chosen_idx])
    out = pd.concat(pieces, ignore_index=True)
    out = out.sample(frac=1.0, random_state=args.seed).reset_index(drop=True)
    if args.max_total_cells > 0 and len(out) > args.max_total_cells:
        out = out.groupby("cell_type", group_keys=False).apply(
            lambda x: x.sample(
                n=max(1, int(round(args.max_total_cells * len(x) / len(out)))),
                random_state=args.seed,
            )
        ).reset_index(drop=True)
        if len(out) > args.max_total_cells:
            out = out.sample(n=args.max_total_cells, random_state=args.seed).reset_index(drop=True)
    out["balanced_order"] = np.arange(len(out), dtype=np.int64)
    return out


def build_expression_memmap(sampled: pd.DataFrame, genes: list[str], args: argparse.Namespace, outdir: Path) -> Path:
    mmap_path = outdir / "balanced_expression_cells_by_genes.float32.mmap"
    shape = (len(sampled), len(genes))
    print(f"Creating memmap {mmap_path} with shape cells x genes = {shape}")
    mm = np.memmap(mmap_path, dtype="float32", mode="w+", shape=shape)
    mm[:] = 0
    gene_set = set(genes)

    pos_by_key = dict(zip(sampled["balanced_order"].values, sampled.index.values))
    # We fill by balanced_order directly, not dataframe index.
    for source_path, sub in sampled.groupby("source_h5ad", dropna=False):
        path = Path(source_path)
        print(f"[EXPR] {path.name}: selected cells={len(sub):,}")
        adata = ad.read_h5ad(path, backed="r")
        try:
            gene_names = get_var_gene_names(adata)
            gene_to_idx = {}
            for i, g in enumerate(gene_names):
                if g and g not in gene_to_idx:
                    gene_to_idx[g] = i
            file_genes = [g for g in genes if g in gene_to_idx]
            file_gene_idx = np.array([gene_to_idx[g] for g in file_genes], dtype=np.int64)
            target_gene_cols = np.array([genes.index(g) for g in file_genes], dtype=np.int64)

            sub_sorted = sub.sort_values("local_index")
            rows_all = sub_sorted["local_index"].to_numpy(dtype=np.int64)
            orders_all = sub_sorted["balanced_order"].to_numpy(dtype=np.int64)
            for start in tqdm(range(0, len(rows_all), args.extract_chunk_size), desc=path.stem, unit="extract", dynamic_ncols=True):
                end = min(start + args.extract_chunk_size, len(rows_all))
                rows = rows_all[start:end]
                orders = orders_all[start:end]
                X = subset_X(adata, rows, file_gene_idx)
                if sp.issparse(X):
                    X = X.toarray()
                X = np.asarray(X, dtype=np.float32)
                mm[orders[:, None], target_gene_cols] = X
                del X
        finally:
            adata.file.close()
            del adata
            gc.collect()
    mm.flush()
    return mmap_path


def write_gsva_tsv_from_memmap(mmap_path: Path, sampled: pd.DataFrame, genes: list[str], out_tsv: Path, args: argparse.Namespace) -> None:
    n_cells = len(sampled)
    n_genes = len(genes)
    mm = np.memmap(mmap_path, dtype="float32", mode="r", shape=(n_cells, n_genes))
    cell_ids = sampled.sort_values("balanced_order")["balanced_cell_id"].astype(str).tolist()
    out_tsv.parent.mkdir(parents=True, exist_ok=True)
    print(f"Writing GSVA expression TSV.gz: {out_tsv}")
    with gzip.open(out_tsv, "wt") as out:
        out.write("gene\t" + "\t".join(cell_ids) + "\n")
        for start in tqdm(range(0, n_genes, args.write_gene_chunk_size), desc="write genes", unit="chunk", dynamic_ncols=True):
            end = min(start + args.write_gene_chunk_size, n_genes)
            block = np.asarray(mm[:, start:end], dtype=np.float32).T  # genes x cells
            for j, gene in enumerate(genes[start:end]):
                vals = "\t".join(f"{x:.6g}" for x in block[j, :])
                out.write(f"{gene}\t{vals}\n")
            del block


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    add_publication_config_argument(ap)
    ap.add_argument("--split-dir", type=Path, default=DEFAULT_SPLIT_DIR)
    ap.add_argument("--manifest", type=Path, default=None)
    ap.add_argument("--pattern", default="*.h5ad")
    ap.add_argument("--gene-set-file", type=Path, default=DEFAULT_GENE_SET_FILE)
    ap.add_argument("--gene-set", default="brain_expanded_merged")
    ap.add_argument("--ppi-gene-file", type=Path, default=None,
                    help="TSV/CSV/TXT containing PPI-network genes. If omitted, falls back to risk/protective genes only.")
    ap.add_argument("--ppi-gene-column", default=None)
    ap.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    ap.add_argument("--cell-type-col", default="subclass")
    ap.add_argument("--fine-cell-type-col", default="subclass")
    ap.add_argument("--disease-col", default="disease")
    ap.add_argument("--donor-col", default=None)
    ap.add_argument("--min-detected-fraction", type=float, default=0.20,
                    help="QC cutoff: fraction of selected/PPI genes with non-zero expression must be greater than this value.")
    ap.add_argument("--max-cells-per-cell-type", type=int, default=10000)
    ap.add_argument("--max-total-cells", type=int, default=0,
                    help="Optional global cap after cell-type balancing. 0 means no global cap.")
    ap.add_argument("--balance-group-col", default="disease_abbr",
                    choices=["disease", "disease_abbr", "donor_id"])
    ap.add_argument("--chunk-size", type=int, default=4096)
    ap.add_argument("--extract-chunk-size", type=int, default=2048)
    ap.add_argument("--write-gene-chunk-size", type=int, default=50)
    ap.add_argument("--seed", type=int, default=13)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    args._publication_config = load_publication_config(args.config)
    return args


def main() -> None:
    args = parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)
    table_dir = args.outdir / "tables"
    table_dir.mkdir(exist_ok=True)

    files = find_h5ad_files(args.split_dir, args.manifest, args.pattern)
    if not files:
        raise SystemExit(f"No h5ad files found in {args.split_dir}")
    print(f"Found split h5ad files: {len(files):,}")

    risk, protective, gs_sub = load_gene_sets(args.gene_set_file, args.gene_set)
    ppi_genes = load_gene_list(args.ppi_gene_file, args.ppi_gene_column)
    if ppi_genes is None:
        print("[WARN] --ppi-gene-file omitted. Using risk/protective gene union only as feature universe.")
        selected_genes = set(risk | protective)
    else:
        selected_genes = set(ppi_genes | risk | protective)  # ensure program genes are retained if present in h5ad
    print(f"risk genes={len(risk):,}; protective genes={len(protective):,}; selected/PPI universe={len(selected_genes):,}")

    if args.dry_run:
        print("Dry-run files:")
        for p in files[:20]: print(p)
        return

    qc, common_genes, _ = first_pass_qc(files, selected_genes, args)
    qc_path = table_dir / "mssm_qc_passed_cells_before_balancing.tsv.gz"
    qc.to_csv(qc_path, sep="\t", index=False, compression="gzip")
    print(f"QC-passed metadata written: {qc_path}; cells={len(qc):,}")

    sampled = balanced_sample(qc, args)
    sampled_path = table_dir / "mssm_balanced_qc_passed_cells.tsv.gz"
    sampled.to_csv(sampled_path, sep="\t", index=False, compression="gzip")
    print(f"Balanced sampled cells written: {sampled_path}; cells={len(sampled):,}")

    # Use genes common to all processed split files so the output matrix has stable rows.
    genes = sorted(set(common_genes))
    # Keep all gene-set genes that are present in common_genes; report missing.
    present_risk = sorted(risk & set(genes))
    present_prot = sorted(protective & set(genes))
    gene_qc = pd.DataFrame({
        "metric": ["selected_genes_common_to_files", "risk_present", "protective_present", "risk_missing", "protective_missing"],
        "value": [len(genes), len(present_risk), len(present_prot), len(risk - set(genes)), len(protective - set(genes))],
    })
    gene_qc.to_csv(table_dir / "mssm_balanced_gene_qc.tsv", sep="\t", index=False)
    pd.DataFrame({"gene": genes}).to_csv(table_dir / "mssm_balanced_expression_genes.tsv", sep="\t", index=False)

    estimated_gb = len(sampled) * len(genes) * 4 / (1024 ** 3)
    print(f"Expression memmap estimate: {estimated_gb:.2f} GB float32 for {len(sampled):,} cells x {len(genes):,} genes")

    mmap_path = build_expression_memmap(sampled, genes, args, args.outdir)
    expr_tsv = args.outdir / "mssm_balanced_ppi_expression_for_gsva.tsv.gz"
    write_gsva_tsv_from_memmap(mmap_path, sampled, genes, expr_tsv, args)

    config = vars(args).copy()
    config.update({
        "n_split_files": len(files),
        "n_qc_passed_cells": int(len(qc)),
        "n_balanced_cells": int(len(sampled)),
        "n_expression_genes": int(len(genes)),
        "expression_tsv": str(expr_tsv),
        "balanced_metadata": str(sampled_path),
        "memmap": str(mmap_path),
    })
    (args.outdir / "step15d_prepare_balanced_expression_config.json").write_text(json.dumps(config, indent=2, default=str))
    print("Done.")
    print(f"expression_file\t{expr_tsv}")
    print(f"metadata_file\t{sampled_path}")


if __name__ == "__main__":
    main()
